---
- name: Deploy Juice Shop with Docker (using shell)
  hosts: atk
  become: true

  tasks:
    - name: Pull Juice Shop docker image
      shell: docker pull bkimminich/juice-shop

    - name: Start Juice Shop container (detached mode)
      shell: docker run -d -p 3000:3000 bkimminich/juice-shop &
