---
- name: Deploy Vulnerable Web Application (DVWA) with Docker (using shell)
  hosts: atk
  become: true

  tasks:
    - name: Pull Vulnerable Web Application (DVWA) docker image
      shell: docker pull vulnerables/web-dvwa

    - name: Start Vulnerable Web Application (DVWA) container (detached mode)
      shell: docker run -d -p 80:80 vulnerables/web-dvwa &