---
- name: Deploy WebGoat with Docker (using shell)
  hosts: atk
  become: true

  tasks:
    - name: Pull WebGoat docker image
      shell: docker pull webgoat/webgoat

    - name: Start WebGoat container (detached mode)
      shell: docker run -d -p 8080:8080 webgoat/webgoat &