variable "VPN_CLIENT" {}
variable "VPN_COMPRESSION" {}
variable "VPN_DNS1" {}
variable "VPN_DNS2" {}
variable "VPN_PRIVATE_IP" {}
variable "DOUGHMAIN" {}
variable "VPN_HUB" {}
variable "VPN_PORT" {}
variable "VPN_PROTOCOL" {}
variable "environment" {}
variable "allowed_inbound_ip_addresses" {}
variable "prefix-vpn-hub" {}
variable "cloudflare-api-user" {}
variable "cloudflare-api-key" {}
variable "cloudflare-zone-id" {}
variable "azure-subscription-id" {}
variable "azure-tenant-id" {}
variable "azure-client-id" {}
variable "azure-client-secret" {}
variable "location" {}
variable "vpnserver_username" {}
variable "vpnserver_password" {}
variable "windows_username" {}
variable "windows_password" {}
variable "vpnserver_hostname" {}
variable "windows_hostname" {}
variable "vpnserver_vmsize" {}
variable "atk_vmsize" {}
variable "vpnserver_nic" {}
variable "lighttpd_template" {}
variable "vars_template" {}
variable "networking_template" {}
variable "dh_pem" {}
variable "server_conf" {}
variable "client_template" {}
variable "ssh_public_key_file" {}
variable "ssh_private_key_file" {}
variable "windows11_vmsize" {}
variable "windows11_nic" {}
variable "vpn_gateway_subnet" {}
variable "vpn_client_subnet" {}
variable "vpn_hub-sg" {}
variable "client-sg" {}
variable "client_PublicIP" {}
variable "atk_hostname" {}
variable "atk_username" {}
variable "atk_password" {}
variable "ubuntu_os_version" {}
variable "obscure-vpn-publisher" {}
variable "obscure-vpn-offer" {}
variable "obscure-vpn-sku" {}
variable "obscure-vpn-version" {}
variable "atk_ip_address" {}
variable "windows_private_ip" {}
variable "windows-publisher" {}
variable "windows-offer" {}
variable "windows-sku" {}
variable "windows-version" {}
variable "ansible-password" {}
variable "atk-vpn-publisher" {}
variable "atk-vpn-offer" {}
variable "atk-vpn-sku" {}
variable "atk-vpn-version" {}
variable "EASYRSA_DN" {}
variable "EASYRSA_REQ_COUNTRY" {}
variable "EASYRSA_REQ_PROVINCE" {}
variable "EASYRSA_REQ_CITY" {}
variable "EASYRSA_REQ_ORG" {}
variable "EASYRSA_REQ_EMAIL" {}
variable "EASYRSA_REQ_OU" {}
variable "EASYRSA_KEY_SIZE" {}
variable "EASYRSA_CA_EXPIRE" {}
variable "EASYRSA_CERT_EXPIRE" {}
variable "EASYRSA_CRL_DAYS" {}
variable "EASYRSA_DIGEST" {}
variable "student" {}
variable "student1" {}
variable "student2" {}
variable "student3" {}
variable "student4" {}
variable "student5" {}
variable "student6" {}
variable "student7" {}
variable "student8" {}
variable "student9" {}
variable "student10" {}
variable "student11" {}
variable "student12" {}
variable "student13" {}
variable "student14" {}
variable "student15" {}
variable "student16" {}
variable "student17" {}
variable "student18" {}
variable "student19" {}
variable "student20" {}
variable "studentIP1" {}
variable "studentIP2" {}
variable "studentIP3" {}
variable "studentIP4" {}
variable "studentIP5" {}
variable "studentIP6" {}
variable "studentIP7" {}
variable "studentIP8" {}
variable "studentIP9" {}
variable "studentIP10" {}
variable "studentIP11" {}
variable "studentIP12" {}
variable "studentIP13" {}
variable "studentIP14" {}
variable "studentIP15" {}
variable "studentIP16" {}
variable "studentIP17" {}
variable "studentIP18" {}
variable "studentIP19" {}
variable "studentIP20" {}










